-- DIAGNOSES Index
IF OBJECT_ID('DIAGNOSES') IS NULL
BEGIN
	 PRINT 'DIAGNOSES TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE name='CHORDS_DIAGNOSES_INDEX' AND object_id = OBJECT_ID('DIAGNOSES'))
BEGIN
	PRINT 'CHORDS_DIAGNOSES_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_DIAGNOSES_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_DIAGNOSES_INDEX ON DIAGNOSES (ENC_ID, DX, ADATE, DIAGPROVIDER);
	 PRINT 'CHORDS_DIAGNOSES_INDEX - CREATED';
END;

-- LAB_RESULTS Index
IF OBJECT_ID('LAB_RESULTS') IS NULL
BEGIN
	 PRINT 'LAB_RESULTS TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE NAME = 'CHORDS_LAB_RESULTS_INDEX' AND object_id = OBJECT_ID('LAB_RESULTS'))
BEGIN
	PRINT 'CHORDS_LAB_RESULTS_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_LAB_RESULTS_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_LAB_RESULTS_INDEX ON LAB_RESULTS(PERSON_ID, TEST_TYPE, LAB_DT, LAB_TM, ORDER_ID)
	 PRINT 'CHORDS_LAB_RESULTS_INDEX - CREATED';
END;

-- PHARMACY Index
IF OBJECT_ID('PHARMACY') IS NULL
BEGIN
	 PRINT 'PHARMACY TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE NAME = 'CHORDS_PHARMACY_INDEX' AND object_id = OBJECT_ID('PHARMACY'))
BEGIN
	PRINT 'CHORDS_PHARMACY_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_PHARMACY_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_PHARMACY_INDEX ON PHARMACY(NDC, RXDATE, PERSON_ID)
	 PRINT 'CHORDS_PHARMACY_INDEX - CREATED';
END;

-- PRESCRIBING Index
IF OBJECT_ID('PRESCRIBING') IS NULL
BEGIN
	 PRINT 'PRESCRIBING TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE NAME = 'CHORDS_PERSCRIBING_INDEX' AND OBJECT_ID = OBJECT_ID('PRESCRIBING'))
BEGIN
	PRINT 'CHORDS_PERSCRIBING_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_PHARMACY_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_PERSCRIBING_INDEX ON PRESCRIBING (PERSON_ID, ENC_ID, RXMD)
	 PRINT 'CHORDS_PERSCRIBING_INDEX - CREATED';
END;

-- PROCEDURES Index
IF OBJECT_ID('PROCEDURES') IS NULL
BEGIN
	 PRINT 'PROCEDURES TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE NAME = 'CHORDS_PROCEDURES_INDEX' AND OBJECT_ID = OBJECT_ID('PROCEDURES'))
BEGIN
	PRINT 'CHORDS_PROCEDURES_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_PROCEDURES_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_PROCEDURES_INDEX ON [PROCEDURES](ENC_ID, PROCDATE, PERFORMINGPROVIDER, ORIGPX, PX, PX_CODETYPE, ROW_ID);
	 PRINT 'CHORDS_PROCEDURES_INDEX - CREATED';
END;

-- SOCIAL_HISTORY Index
IF OBJECT_ID('SOCIAL_HISTORY') IS NULL
BEGIN
	 PRINT 'SOCIAL_HISTORY TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE NAME = 'CHORDS_SOCIAL_HISTORY_INDEX' AND OBJECT_ID = OBJECT_ID('SOCIAL_HISTORY'))
BEGIN
	PRINT 'CHORDS_SOCIAL_HISTORY_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_SOCIAL_HISTORY_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_SOCIAL_HISTORY_INDEX ON SOCIAL_HISTORY (PERSON_ID, CONTACT_DATE);
	 PRINT 'CHORDS_SOCIAL_HISTORY_INDEX - CREATED';
END;

-- VITAL_SIGNS Index
IF OBJECT_ID('VITAL_SIGNS') IS NULL
BEGIN
	 PRINT 'VITAL_SIGNS TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE NAME = 'CHORDS_VITAL_SIGNS_INDEX' AND OBJECT_ID = OBJECT_ID('VITAL_SIGNS'))
BEGIN
	PRINT 'CHORDS_VITAL_SIGNS_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_VITAL_SIGNS_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_VITAL_SIGNS_INDEX ON VITAL_SIGNS (PERSON_ID, MEASURE_DATE, MEASURE_TIME);
	 PRINT 'CHORDS_VITAL_SIGNS_INDEX - CREATED';
END;

-- VITAL_SIGNS Index
IF OBJECT_ID('TUMOR') IS NULL
BEGIN
	 PRINT 'TUMOR TABLE DOES NOT';
END;
ELSE
IF EXISTS (SELECT *  FROM sys.indexes  WHERE NAME = 'CHORDS_TUMOR_INDEX' AND OBJECT_ID = OBJECT_ID('TUMOR'))
BEGIN
	PRINT 'CHORDS_TUMOR_INDEX ALREADY EXISTS';
END;
ELSE
BEGIN
	 PRINT 'CREATING CHORDS_TUMOR_INDEX';
	 CREATE CLUSTERED INDEX CHORDS_TUMOR_INDEX ON TUMOR (PERSON_ID, [SEQUENCE]);
	 PRINT 'CHORDS_TUMOR_INDEX - CREATED';
END;