IF OBJECT_ID('CHORDS_VDW31_PRINCIPAL_DX_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_PRINCIPAL_DX_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_PRINCIPAL_DX_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_PRINCIPAL_DX_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_PRINCIPAL_DX_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_PRINCIPAL_DX_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'P', N'Principal Dx' ), ( 
		   N'N', N'Not Principal Dx' ), ( 
		   N'X', N'Principal Dx Status not classifiable' );
	PRINT 'CHORDS_VDW31_PRINCIPAL_DX_LU - Complete';
END;