IF OBJECT_ID('CHORDS_VDW31_CONFIDENCE_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_CONFIDENCE_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_CONFIDENCE_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_CONFIDENCE_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_CONFIDENCE_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_CONFIDENCE_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'E', N'Excellent' ), ( 
		   N'F', N'Fair' ), ( 
		   N'P', N'Poor' );
	PRINT 'CHORDS_VDW31_CONFIDENCE_LU - Complete';
END;