IF OBJECT_ID('CHORDS_VDW31_GENDER_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_GENDER_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_GENDER_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_GENDER_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(25) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_GENDER_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_GENDER_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'F', N'Female' ), ( 
		   N'M', N'Male' ), ( 
		   N'U', N'Unknown' ), ( 
		   N'O', N'Other' );
	PRINT 'CHORDS_VDW31_GENDER_LU - Complete';
END;