IF OBJECT_ID('CHORDS_VDW31_PX_CODETYPE_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_PX_CODETYPE_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_PX_CODETYPE_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_PX_CODETYPE_LU]
	( 
				 [ABBREVIATION] nvarchar(2) NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_PX_CODETYPE_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_PX_CODETYPE_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'09', N'ICD-9-CM' ), ( 
		   N'10', N'ICD-10-CM' ), ( 
		   N'11', N'ICD-11-CM' ), ( 
		   N'C4', N'CPT-4' ), ( 
		   N'H4', N'HCPCS-4' ), ( 
		   N'RV', N'Revenue code' ), ( 
		   N'LO', N'Local homegrown' ), ( 
		   N'OT', N'Other' );
	PRINT 'CHORDS_VDW31_PX_CODETYPE_LU - Complete';
END;