IF OBJECT_ID('CHORDS_VDW31_DISCHARGE_DISPOSITION_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_DISCHARGE_DISPOSITION_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_DEPARTMENT_LU - Creating';
	CREATE TABLE CHORDS_VDW31_DISCHARGE_DISPOSITION_LU
	( 
				 ABBREVIATION nchar NOT NULL,
				 DESCRIPTION nvarchar(50) NOT NULL, 
				 CONSTRAINT PK_CHORDS_VDW31_DISCHARGE_DISPOSITION_LU PRIMARY KEY CLUSTERED(ABBREVIATION ASC)
	)
	ON [PRIMARY];
	INSERT INTO CHORDS_VDW31_DISCHARGE_DISPOSITION_LU( 
		ABBREVIATION, 
		DESCRIPTION )
	VALUES( 
		   N'A', N'Alive' ), ( 
		   N'E', N'Expired' ), ( 
		   N'U', N'Unknown' );
	PRINT 'CHORDS_VDW31_DISCHARGE_DISPOSITION_LU - Complete';
END;