IF OBJECT_ID('CHORDS_VDW31_POSITION_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_POSITION_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_POSITION_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_POSITION_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_POSITION_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_POSITION_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'1', N'Sitting' ), ( 
		   N'2', N'Standing' ), ( 
		   N'3', N'Supine' );
	PRINT 'CHORDS_VDW31_POSITION_LU - Complete';
END;