IF OBJECT_ID('CHORDS_VDW31_CAUSETYPE_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_CAUSETYPE_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_CAUSETYPE_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_CAUSETYPE_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_CAUSETYPE_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_CAUSETYPE_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'I', N'Immediate/Primary' ), ( 
		   N'U', N'Underlying' ), ( 
		   N'C', N'Contributory' ), ( 
		   N'O', N'Other' );
	PRINT 'CHORDS_VDW31_CAUSETYPE_LU - Creating';
END;