IF OBJECT_ID('CHORDS_VDW31_LANG_USAGE_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_LANG_USAGE_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_LANG_USAGE_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_LANG_USAGE_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_LANG_USAGE_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_LANG_USAGE_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'S', N'Spoken (or signed)' ), ( 
		   N'W', N'Written' ), ( 
		   N'B', N'Both spoken and written' ), ( 
		   N'U', N'Unknown' );
	PRINT 'CHORDS_VDW31_LANG_USAGE_LU - Complete';
END;