IF OBJECT_ID('CHORDS_VDW31_YNU_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_YNU_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_YNU_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_YNU_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_YNU_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_YNU_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'Y', N'Yes' ), ( 
		   N'N', N'No' ), ( 
		   N'U', N'Unknown' );
	PRINT 'CHORDS_VDW31_YNU_LU - Complete';
END;