IF OBJECT_ID('CHORDS_VDW31_STAT_LU') IS NOT NULL
BEGIN
	PRINT 'CHORDS_VDW31_STAT_LU Already Exists';
END;
ELSE
BEGIN
	PRINT 'CHORDS_VDW31_STAT_LU - Creating';
	CREATE TABLE [CHORDS_VDW31_STAT_LU]
	( 
				 [ABBREVIATION] nchar NOT NULL, 
				 [DESCRIPTION] nvarchar(50) NOT NULL, 
				 CONSTRAINT [PK_CHORDS_VDW31_STAT_LU] PRIMARY KEY CLUSTERED([ABBREVIATION] ASC)
	)
	ON [PRIMARY];
	INSERT INTO [CHORDS_VDW31_STAT_LU]( 
		[ABBREVIATION], 
		[DESCRIPTION] )
	VALUES( 
		   N'E', N'Expedite' ), ( 
		   N'S', N'Stat' ), ( 
		   N'R', N'Routine' ), ( 
		   N'U', N'Unknown or missing' );
	PRINT 'CHORDS_VDW31_STAT_LU - Complete';
END;