TRUNCATE TABLE dbo.CAUSE_OF_DEATH;
TRUNCATE TABLE dbo.DEATH;
TRUNCATE TABLE dbo.DEMOGRAPHICS;
TRUNCATE TABLE dbo.DIAGNOSES;
TRUNCATE TABLE dbo.ENCOUNTERS;
TRUNCATE TABLE dbo.ENROLLMENT;
TRUNCATE TABLE dbo.EVERNDC;
TRUNCATE TABLE dbo.LAB_RESULTS;
TRUNCATE TABLE dbo.LANGUAGES;
TRUNCATE TABLE dbo.PHARMACY;
TRUNCATE TABLE dbo.PROCEDURES;
TRUNCATE TABLE dbo.PROVIDER_SPECIALTY;
TRUNCATE TABLE dbo.SOCIAL_HISTORY;
TRUNCATE TABLE dbo.TUMOR;
TRUNCATE TABLE dbo.VITAL_SIGNS;

